name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  api-tests:
    name: API Tests
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run API Tests
        run: ./mvnw clean test -pl api-tests

      - name: Generate Allure Report
        if: always()
        run: allure generate api-tests/target/allure-results -o api-tests/target/allure-report --clean

      - name: Deploy API Report
        if: always()
        run: rsync -avz --delete api-tests/target/allure-report/ /srv/apps/agibank-challenge-reports/api/

      - name: Push API Metrics to InfluxDB
        if: always()
        run: |
          chmod +x infra/scripts/push-allure-metrics.sh
          bash infra/scripts/push-allure-metrics.sh \
            api-tests/target/allure-report \
            api \
            "${{ github.ref_name }}" \
            "${{ github.sha }}"
        continue-on-error: true

  web-tests:
    name: Web Tests
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Playwright System Dependencies
        run: sudo npx -y playwright install-deps chromium

      - name: Install Playwright Browsers
        run: ./mvnw exec:java -pl web-tests -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install chromium"

      - name: Run Web Tests
        run: ./mvnw clean test -pl web-tests

      - name: Generate Allure Report
        if: always()
        run: allure generate web-tests/target/allure-results -o web-tests/target/allure-report --clean

      - name: Deploy Web Report
        if: always()
        run: rsync -avz --delete web-tests/target/allure-report/ /srv/apps/agibank-challenge-reports/web/

      - name: Push Web Metrics to InfluxDB
        if: always()
        run: |
          chmod +x infra/scripts/push-allure-metrics.sh
          bash infra/scripts/push-allure-metrics.sh \
            web-tests/target/allure-report \
            web \
            "${{ github.ref_name }}" \
            "${{ github.sha }}"
        continue-on-error: true
